classic: false
blocks:
  - permission
  - user
  - group
  - size
  - date
  - name

color:
  when: auto
  # Possible values: default, custom
  # When "custom" is set, lsd will look in the config directory for `colors.yaml`.
  theme: default

date: date
dereference: false

icons:
  when: auto
  theme: fancy
  separator: " "

indicators: true

layout: grid

# == Recursion ==
recursion:
  # Whether to enable recursion.
  # Possible values: false, true
  enabled: false
  # How deep the recursion should go. This has to be a positive integer. Leave
  # it unspecified for (virtually) infinite.
  # depth: 3

size: default

# == Sorting ==
sorting:
  column: name
  reverse: false
  dir-grouping: first
no-symlink: false
total-size: true
hyperlink: auto
symlink-arrow: ⇒
header: false
literal: true
truncate-owner:
  after:
  marker: ""
